version: '3.4'
services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - base_url=//profimap.ru
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
    network_mode: 'host'
    ports:
      - '3001:3001'
    command:
      'npm start'
