version: '3.4'
services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - node_env=production
        - base_url=http://127.0.0.1:3001
        - browser_base_url=https://panel.profimap.ru
        - yandex_metrika=${YANDEX_METRIKA}
        - sentry_dsn=${SENTRY_DSN}
        - recaptcha_site_key=${RECAPTCHA_SITE_KEY}
    restart: always
    environment:
      - HOST=127.0.0.1
      - PORT=3001
      - LOG_LEVEL=info
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRED_TIME=${JWT_EXPIRED_TIME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - VKONTAKTE_CLIENT_ID=${VKONTAKTE_CLIENT_ID}
      - VKONTAKTE_CLIENT_SECRET=${VKONTAKTE_CLIENT_SECRET}
      - SENDGRID_KEY=${SENDGRID_KEY}
      - STATIC_DIR=${STATIC_DIR}
      - STATIC_URL=${STATIC_URL}
      - ROBOKASSA_MERCHANT_LOGIN=${ROBOKASSA_MERCHANT_LOGIN}
      - ROBOKASSA_PASSWORD1=${ROBOKASSA_PASSWORD1}
      - ROBOKASSA_PASSWORD2=${ROBOKASSA_PASSWORD2}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    network_mode: 'host'
    volumes:
      - ${STATIC_DIR}:/opt/images
    ports:
      - '3001:3001'
    command:
      'npm start'
