version: '3.4'
services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - base_url=https://panel.profimap.ru
        - yandex_metrika=56011483
    restart: always
    environment:
      - HOST=127.0.0.1
      - PORT=3001
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRED_TIME=${JWT_EXPIRED_TIME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - STATIC_DIR=${STATIC_DIR}
      - STATIC_URL=${STATIC_URL}
    network_mode: 'host'
    volumes:
      - ${STATIC_DIR}:/opt/images:ro
    ports:
      - '3001:3001'
    command:
      'npm start'
