version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - BASE_URL=//profimap.ru
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - '3001:3001'
    command:
      'npm start'