version: '3.4'
services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - base_url=http://dev.profimap.ru
    restart: always
    environment:
      - HOST=127.0.0.1
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
    network_mode: 'host'
    ports:
      - '3000:3000'
    command:
      'npm run start:dev'
