version: '3.4'
services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - node_env=development
        - base_url=http://127.0.0.1:3000
        - browser_base_url=https://dev.panel.profimap.ru
        - yandex_metrika=${YANDEX_METRIKA}
        - sentry_dsn=${SENTRY_DSN}
    restart: always
    environment:
      - HOST=127.0.0.1
      - PORT=3000
      - LOG_LEVEL=info
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRED_TIME=${JWT_EXPIRED_TIME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - VKONTAKTE_CLIENT_ID=${VKONTAKTE_CLIENT_ID}
      - VKONTAKTE_CLIENT_SECRET=${VKONTAKTE_CLIENT_SECRET}
      - SENDGRID_KEY=${SENDGRID_KEY}
      - STATIC_DIR=${STATIC_DIR}
      - STATIC_URL=${STATIC_URL}
    network_mode: 'host'
    volumes:
      - ${STATIC_DIR}:/opt/images
    ports:
      - '3000:3000'
    command:
      'npm run start:dev'
